if: branch =~ ^master$|^release|^development|^ci

language: php

php: 7.2

before_install:
  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d

  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ~/.ssh/id_rsa
  - ssh -i ~~/.ssh/id_rsa travis@47.240.108.57

addons:
  ssh_known_hosts: 47.240.108.57

install:
  - php -v
  - php -m
  - echo ${PASSWORD}
  - echo ${PASSWORD1}
  - echo ${TRAVIS_BRANCH}

#before_script:

script: skip

after_success:
  - ls -ll
  - cd ~
  - ls -ll

#before_deploy:

#deploy:

#after_deploy:
