if: branch =~ ^master$|^release|^development|^ci

language: php

php: 7.2

install:
  - php -v
  - php -m
  - echo $PASSWORD
  - echo $PASSWORD1

script: skip

before_install:
  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d

addons:
  ssh_known_hosts: 47.240.108.57

after_success:
  - ls -ll
  - cd ~
  - ls -ll