if: branch =~ ^master$|^release|^development|^ci

language: php

group: stable
dist: trusty
php: 7.4
os: linux
sudo: required
services:
  - docker
branches:
  only:
    - master
    - release
    - development

before_install:
#  - openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
#    -in id_rsa.enc -out ~/.ssh/id_rsa -d

#  - eval "$(ssh-agent -s)"
#  - chmod 600 ~/.ssh/id_rsa
#  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#  - ssh-add ~/.ssh/id_rsa

addons:
#  ssh_known_hosts:
#    - ${IP}

install:
#  - rm composer.lock
  - composer global require hirak/prestissimo
  - composer install

#before_script:

script: skip

cache:
  directories:
    - $HOME/.composer/cache/files

after_success:
#  - ls -ll
#  - tar zcvf file.tar.gz README.md
#  - scp -o stricthostkeychecking=no file.tar.gz ${USER}@${IP}:/home/travis
#  - rm -rf file.tar.gz
#  - ls -ll

before_deploy:
  - docker build -t $DOCKER_USERNAME/test-$TRAVIS_BRANCH:$TRAVIS_BUILD_NUMBER .

deploy:
  - provider: script
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_USERNAME/test-$TRAVIS_BRANCH
    skip_cleanup: true
    on:
      all_branches: true